apiVersion: batch/v1
kind: CronJob
metadata:
  name: nightly-backup
spec:
  schedule: "0 2 * * *"
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup-worker
              image: curlimages/curl:latest # Small footprint
              command: ["/bin/sh", "-c", "echo 'Backing up data...'"]
          restartPolicy: OnFailure
